"""Initial migration with updated Deal model

Revision ID: 8eaeb8f956e8
Revises: 
Create Date: 2025-07-30 00:56:04.958757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8eaeb8f956e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deal_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('seller_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('seller_mobile', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('seller_id_card', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('seller_address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('approved_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('approved_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('approval_notes', sa.Text(), nullable=True))
        batch_op.alter_column('seller_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key('fk_deal_approved_by_user', 'user', ['approved_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deal', schema=None) as batch_op:
        batch_op.drop_constraint('fk_deal_approved_by_user', type_='foreignkey')
        batch_op.alter_column('seller_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('approval_notes')
        batch_op.drop_column('approved_at')
        batch_op.drop_column('approved_by')
        batch_op.drop_column('seller_address')
        batch_op.drop_column('seller_id_card')
        batch_op.drop_column('seller_mobile')
        batch_op.drop_column('seller_name')
        batch_op.drop_column('deal_type')

    # ### end Alembic commands ###
