"""Add OwnershipHistory table

Revision ID: add_ownership_history
Revises: 8eaeb8f956e8
Create Date: 2025-07-30 01:15:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_ownership_history'
down_revision = '8eaeb8f956e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ownership_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('previous_owner_id', sa.Integer(), nullable=True),
    sa.Column('new_owner_id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=True),
    sa.Column('transfer_date', sa.DateTime(), nullable=True),
    sa.Column('transfer_type', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deal.id'], ),
    sa.ForeignKeyConstraint(['new_owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['previous_owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ownership_history')
    # ### end Alembic commands ###
